version: '3.7'
services:
  web:
    build:
      ./shortener_project
    env_file:
      - .env.dev
    command: gunicorn shortener_project.wsgi:application --bind ${GUNICORN_PORT}
    ports:
      - 8000:8000
    volumes:
      - ./shortener_project/:/usr/src/app/
      - "static:/static"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  static:
