version: '3.7'
services:
  web:
    build:
      ./shortener_project
    env_file:
      - .env.dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./shortener_project/:/usr/src/app/